version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven:
    jobs:
      - build:
          docker:
            - image: circleci/openjdk:stretch
              auth:
                username: agusvelez5
                password: $DOCKERHUB_PASSWORD  
          steps:
            - checkout
            - run: ./mvnw -Dmaven.test.skip=true package
            - persist_to_workspace:
                root: ./
                paths:
                  - target/